// Generated by using Rcpp::compileAttributes() -> do not edit by hand
#include <RcppEigen.h>
#include <Rcpp.h>
using namespace Rcpp;

Rcpp::NumericMatrix rc_gpr_capacity_cpp(
    Rcpp::NumericMatrix, Rcpp::IntegerVector, Rcpp::IntegerVector,
    Rcpp::IntegerVector, std::string, std::string
);

RcppExport SEXP _RegCompassR_rc_gpr_capacity_cpp(
    SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f
) {
BEGIN_RCPP
    Rcpp::RObject out;
    Rcpp::RNGScope scope;
    out = Rcpp::wrap(rc_gpr_capacity_cpp(
        Rcpp::as<Rcpp::NumericMatrix>(a),
        Rcpp::as<Rcpp::IntegerVector>(b),
        Rcpp::as<Rcpp::IntegerVector>(c),
        Rcpp::as<Rcpp::IntegerVector>(d),
        Rcpp::as<std::string>(e),
        Rcpp::as<std::string>(f)
    ));
    return out;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RegCompassR_rc_gpr_capacity_cpp",
     (DL_FUNC) &_RegCompassR_rc_gpr_capacity_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_RegCompassR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
