# Generated by using Rcpp::compileAttributes() -> do not edit by hand

.rc_gpr_capacity_cpp <- function(
    score, reaction_group_offset, group_gene_offset, gene_index,
    and_method, or_method
) {
    .Call(
        `_RegCompassR_rc_gpr_capacity_cpp`,
        score, reaction_group_offset, group_gene_offset, gene_index,
        and_method, or_method
    )
}

.rc_corda2_scan_flux_cpp <- function(
    flux, class_code, track_code, threshold
) {
    .Call(
        `_RegCompassR_rc_corda2_scan_flux_cpp`,
        flux, class_code, track_code, threshold
    )
}
